services:
  postgres95:
    image: postgres:9.5
    platform: linux/amd64    
    restart: always
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=testdb
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "55413:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=testdb
  mysql56:
    image: mysql:5.6
    platform: linux/amd64
    restart: always
    ports:
      - "33306:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "33308:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
      - LANG=C.UTF-8
    volumes:
      - ./testdata/ddl/mysql:/docker-entrypoint-initdb.d
  mariadb:
    image: mariadb:10.5
    restart: always
    ports:
      - "33309:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - "11433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MSSQLServer-Passw0rd
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "18000:8000"
  mongo:
    image: mongo:4.4.18
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=test
    volumes:
      - ./testdata/ddl/mongo:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
  clickhouse:
    image: clickhouse/clickhouse-server:24.4
    restart: always
    environment:
      - CLICKHOUSE_DB=testdb
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ./testdata/ddl/clickhouse:/docker-entrypoint-initdb.d
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/?query=SELECT%201 || exit 1
    ports:
      - "8123:8123"
      - "9000:9000"
