name: release test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/release-test.yml
      - .goreleaser/*.yml

jobs:
  darwin-release-test:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup
        run: |
          brew install sqlite3

      - name: Install
        run: |
          go install github.com/k1LoW/tbls@latest
          tbls version

      - name: Run GoReleaser (dry-run)
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: --config .goreleaser/darwin.yml --clean --snapshot --skip=publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-release-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install sqlite3 gcc-aarch64-linux-gnu

      - name: Install aws-cli
        uses: isbang/setup-awscli@v0.1.0

      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install
        run: |
          go install github.com/k1LoW/tbls@latest
          tbls version

      - name: Run GoReleaser (dry-run)
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: --config .goreleaser/linux.yml --clean --snapshot --skip=publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-release-test:
    strategy:
      matrix:
        os: [windows-2019, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Install packages
        run: |
          choco install sqlite

      - name: Install aws-cli
        uses: isbang/setup-awscli@v0.1.0

      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install
        run: |
          go install github.com/k1LoW/tbls@latest
          tbls version

      - name: Run GoReleaser (dry-run)
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: --config .goreleaser/windows.yml --clean --snapshot --skip=publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
